include: package:lints/recommended.yaml

analyzer:
  errors:
    # Allow deprecated members to be used within the same package
    # This is necessary for backward compatibility during deprecation periods
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    # Additional recommended rules for package development
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - directives_ordering
    - test_types_in_equals
    - throw_in_finally
