name: isolate_plus
version: 2.2.1
description: >-
  A modernized fork of dart-archive/isolate. Utility functions and classes 
  related to the 'dart:isolate' library. Supports Dart SDK 3.3.0+.
homepage: https://github.com/arcticfox1919/isolate_plus
repository: https://github.com/arcticfox1919/isolate_plus

environment:
  sdk: '>=3.3.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
